### ISSUE TITLE
package.elm-lang.org is down

### ISSUE THREAD

**Issue by lukaszsamson** [elm-lang/package.elm-lang.org#259]
CI build is failing with:
```
ERROR in ./elm/Main.elm
Module build failed: Error: Compiler process exited with error Compilation failed
Running elm-make with sysconfcpus -n 2
Error: The following HTTP request failed.
<http://package.elm-lang.org/all-packages?elm-package-version=0.18>

FailedConnectionException2 "package.elm-lang.org" 80 False connect: does not exist (Connection refused)

    at ChildProcess.<anonymous> (/home/myapp/node_modules/node-elm-compiler/index.js:141:27)
    at emitTwo (events.js:126:13)
    at ChildProcess.emit (events.js:214:7)
    at maybeClose (internal/child_process.js:925:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:209:5)
 @ ./js/app.js 25:0-43
```
And I cannot reach the server from my machine as well.
Anyway, it's rather strange that elm-make needs to connect anywhere at all.

**Comment by BrianHicks** [comment]
hi @lukaszsamson, this is known. Please watch Slack for updates.

**Comment by BrianHicks** [comment]
it's up again, hooray!
